site_uuid = "find it in the Cloudflare dashboard"
# A command to get the API token of the Cloudflare API. The token should be on
# the first line of output (the rest is discarded)
api_token_cmd = "call your password manager (or cat a file if you really want to)"
